config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  resources :trains
  resources :stops

  namespace :admin do
    resources :trains
    resources :routes
    resources :stops
  end
end

app/models/route.rb
class Route < ActiveRecord::Base
end

app/models/stop.rb
class Stop < ActiveRecord::Base
end

app/models/train.rb
class Train < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < ApplicationController
  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def route_params
    params.require(:route).permit(:name, :train_id)
  end
end

app/controllers/admin/stops_controller.rb
class Admin::StopsController < ApplicationController

  def new
    @stop = Stop.new
  end

  def create
    @stop = Stop.new(stop_params)
    if @stop.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def stop_params
    params.require(:stop).permit(:name, :train_id, :parent_station)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < ApplicationController
  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def train_params
    params.require(:train).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    red = Train.find_by(name: "Red")
    @redstops = Stop.where(train_id: red.id)

    blue = Train.find_by(name: "Blue")
    @bluestops = Stop.where(train_id: blue.id)

    orange = Train.find_by(name: "Orange")
    @orangestops = Stop.where(train_id: orange.id)
  end
end

app/controllers/stops_controller.rb
require 'net/http'
require 'uri'

class StopsController < ApplicationController

  def show
    stop = Stop.find(params[:id])
    station = stop.parent_station
    api_key = ENV["API_KEY"]
    uri = URI("http://realtime.mbta.com/developer/api/v2/predictionsbystop?api_key=#{api_key}&stop=#{station}&format=json")
    response = Net::HTTP.get(uri)
    @station_data = JSON.parse(response)
  end

  def new
    @stop = Stop.new
  end

  def create
    @stop = Stop.new(stop_params)
    if @stop.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def stop_params
    params.require(:stop).permit(:name, :train_id, :parent_station)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def train_params
    params.require(:train).permit(:name)
  end
end

app/views/admin/routes/new.html.erb
<%= form_for @route do |f| %>
  <%= f.label :train_id %>
  <%= f.collection_select(:train_id, Train.all, :id, :name) %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :number %>
  <%= f.number_field :number %>

  <%= f.label :direction %>
  <%= f.select :direction, options_for_select(["Northbound", "Southbound"]) %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/stops/new.html.erb
<%= form_for @stop do |f| %>
  <%= f.label :train_id %>
  <%= f.collection_select(:train_id, Train.all, :id, :name) %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :parent_station %>
  <%= f.text_field :parent_station %>
  <%= f.submit "Submit" %>
<% end %>

app/views/admin/trains/new.html.erb
<%= form_for @train do |f| %>
  <%= f.label :name, "Train" %>
  <%= f.text_field :name %>

  <%= f.submit "Submit" %>
<% end %>

app/views/homes/index.html.erb
<%= image_tag "subway.jpg", class: "bgIMG" %>


<div id="train_index" class="row">
  <div class="larger-3 medium-3 columns">
    <%= image_tag("redline.png") %>
    <a class="button expand medium" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false">Redline</a>
    <ul id="drop1" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
      <% @redstops.each do |stop| %>
        <li><%= link_to "#{stop.name}", stop_path(stop.id) %></li>
      <% end %>
    </ul><br>
  </div>

  <div class="larger-3 medium-3 columns">
    <%= image_tag("blueline.png") %>
    <a class="button expand" data-dropdown="drop2" aria-controls="drop2" aria-expanded="false">Blueline</a>
    <ul id="drop2" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
      <% @bluestops.each do |stop| %>
        <li><%= link_to "#{stop.name}", stop_path(stop.id) %></li>
      <% end %>
    </ul><br>
  </div>

  <div class="larger-3 medium-3 columns">
    <%= image_tag("orangeline.png") %>
    <a class="button expand" data-dropdown="drop3" aria-controls="drop3" aria-expanded="false">Orangeline</a>
    <ul id="drop3" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
      <% @orangestops.each do |stop| %>
        <li><%= link_to "#{stop.name}", stop_path(stop.id) %></li>
      <% end %>
    </ul>
  </div>

  <div class="larger-3 medium-3 columns">
    <%= image_tag("greenline.png") %>
    <a class="button expand" data-dropdown="drop4" aria-controls="drop4" aria-expanded="false">GreenLine</a>
    <ul id="drop4" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
      Green Line stops coming soon!
    </ul>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uhnjehwah(Whens it coming?)</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Uhnjehwah (Whens it coming?)</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/routes/new.html.erb
<%= form_for @route do |f| %>
  <%= f.label :train_id %>
  <%= f.collection_select(:train_id, Train.all, :id, :name) %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :number %>
  <%= f.number_field :number %>

  <%= f.label :direction %>
  <%= f.select :direction, options_for_select(["Northbound", "Southbound"]) %>

  <%= f.submit "Submit" %>
<% end %>

app/views/stops/show.html.erb
<%= image_tag "subway.jpg", :class => "bgIMG" %>

<div class= "row ">
  <div id="stationbox" class="large-12 medium-12 columns">
    <h1><%= @station_data["stop_name"] %>: <%= @station_data["mode"][0]["route"][0]["route_name"] %> </h1>
  </div>
</div>

<div class="row">
  <p><% @station_data["mode"][0]["route"].each do |route| %></p>
    <% route["direction"].each do |direction| %>
      <div class="large-3 medium-3 columns">
        <div id="stopbox">
          <p><%= direction["direction_name"] %> Arrivals:</p>
            <% direction["trip"].each do |trip| %>
              <p><%= trip["trip_headsign"] %> <%= trip["pre_away"].to_i/60 %> mins</p>
            <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class= "row">
  <div id="stationbox" class="large-12 medium-12 columns">
    <% @station_data["alert_headers"].each do |alert| %>
      <p><%= alert["effect_name"] %><%= alert["header_text"] %></p>
    <% end %>
  </div>
</div>

app/views/trains/new.html.erb
<%= form_for @train do |f| %>
  <%= f.label :name, "Train" %>
  <%= f.text_field :name %>

  <%= f.submit "Submit" %>
<% end %>